name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: git clone https://github.com/frappe/frappe_docker.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: get versions
        id: get-versions
        run: |
          JSON=$(cat <<EOF
          [
            {"url":"https://github.com/frappe/erpnext","branch":"v15.54.3"},
            {"url":"https://github.com/frappe/lms","branch":"v2.26.0"}
          ]
          EOF
          )
          
          echo "APPS=$(echo $JSON | base64 -w 0)" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frappe_docker
          file: ./frappe_docker/images/custom/Containerfile
          push: true
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            FRAPPE_BRANCH=v15.58.0
            PYTHON_VERSION=3.11.9
            NODE_VERSION=18.18.2
            APPS_JSON_BASE64=${{ steps.get-versions.outputs.APPS }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frappe-demo:${{ github.ref_name }}